### PR TITLE
fix: extract revision numbers only from the revision dicts

### PR DESCRIPTION
**Pull request by linostar**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
Fix issue in https://github.com/canonical/oci-factory/actions/runs/8073081089/job/22056099446 caused by eol value being misused as a revisions dict.

### CODE REVIEW

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
this is not gonna fix it. the proposed change is redundant and is actually introducing an error, that is `revision` may not be defined

**Comment by linostar** [comment]
> this is not gonna fix it. the proposed change is redundant and is actually introducing an error, that is `revision` may not be defined

@cjdcordeiro I handled the case where `revision` is not defined. But why do you say the proposed change is redundant? The issue originates from the fact that `targets` can be either a revision dict or a eol datetime string, so this makes it extracts the revision number only in the former case.

**Comment by linostar** [comment]
@cjdcordeiro done.

**Review by cjdcordeiro — APPROVED** [review]

**Comment by cjdcordeiro** [comment]
Thanks

**Pull request merged**
