### PR TITLE
fix(ci): upgrade skopeo to v1.15 to fix test fails

### PR DESCRIPTION
**Pull request by zhijie-yang**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description

This boosts the skopeo used in test and vulnerability scan workflows to v1.15 to fix "read/write on closed pipe" and "client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version" errors.

### CODE REVIEW

**Review by SamirPS — COMMENTED** [review]
LGTM but why you don't use the v1.15.1 tag?

**Comment by zhijie-yang** [comment]
Good catch, updated to v1.15.1.

**Review by SamirPS — COMMENTED** [review]
LGTM

**Review by linostar — APPROVED** [review]
LGTM, thanks.

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
this issue seems unrelated to the skopeo vs docker conflict: https://github.com/canonical/oci-factory/actions/runs/9516977462/job/26234899144?pr=199, but introduced by this PR - it should be looked at before merging

**Review by cjdcordeiro — APPROVED** [review]
LGTM ty!

**Pull request merged**
