### PR TITLE
feat: add karma rock

### PR DESCRIPTION
**Pull request by lucabello**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description

This PR adds the Karma ROCK to the oci-factory.

### Related issues

#165

### CODE REVIEW

**Comment by lucabello** [comment]
Looks like CI failed on a random network hiccup :)

**Comment by linostar** [comment]
> Looks like CI failed on a random network hiccup :)

re-running...

**Review by linostar — APPROVED** [review]
LGTM, thanks.

**Comment by lucabello** [comment]
@cjdcordeiro can this be merged or is it waiting for something? :)

**Comment by cjdcordeiro** [comment]
@lucabello it's waiting for https://github.com/canonical/oci-factory/issues/165#issuecomment-2068892075

**Review by cjdcordeiro — APPROVED** [review]
All good to go. thanks

**Pull request merged**
