### PR TITLE
feat: add python3.11

### PR DESCRIPTION
**Pull request by zhijie-yang**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
This PR adds Python 3.11 to the OCI Factory.

### CODE REVIEW

**Review by linostar — APPROVED** [review]
LGTM, thanks!

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
we do **not** want to publish 3.11. that would be a Pro rock.

**Comment by cjdcordeiro** [comment]
we still need to rebuild 3.8 and 3.12. Have there been no changes to those since the last oci factory PR?

**Comment by zhijie-yang** [comment]
There are. Besides the change for python 3.10, there is only a minor change: The chisel version used in the Dockerfile of python 3.8 is been bumped from 0.9.0 to 0.10.0. Since the python images are all build by the oci factory with rockcraft, this should make no difference.

**Comment by cjdcordeiro** [comment]
ok then we still need your 3.10 change and I'll manually re-trigger 3.8

**Pull request closed without merging**
