### PR TITLE
feat: add prometheus-pushgateway rock

### PR DESCRIPTION
**Pull request by lucabello**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
This PR adds the Prometheus Pushgateway ROCK to the oci-factory.

Please note that this should go to a new `prometheus-pushgateway` repository that's yet to be created.

### Related issues

#75

### CODE REVIEW

**Review by cjdcordeiro — CHANGES_REQUESTED** [review]
hum...I wonder where the efficiency fails are coming from. @tigarmo has made a [significant feat recently](https://github.com/canonical/rockcraft/pull/417) to avoid duplication of contents inside the rock, so I wonder why this is happening.

@lucabello did you try building it locally? If so, does `dive` complain about the same efficiency issue? If you've built your image locally, what size did you get?

**Comment by cjdcordeiro** [comment]
FYI @tigarmo @lucabello I've just built this ROCK with the latest rockcraft version, and indeed got the inefficiency. A quick inspection showed `/usr/lib/x86_64-linux-gnu/libc.so.6` twice in the rock, with the same size, ownership and permissions. I didn't dig any further yet. @tigarmo could u give it a try?

**Comment by cjdcordeiro** [comment]
riiighhht....once the base image is updated in ECR, this should be fixed then?

**Comment by tigarmo** [comment]
Yes
check it out: same file sizes, different sha1s:
```
> file /root/prime/lib/x86_64-linux-gnu/libc.so.6 
/root/prime/lib/x86_64-linux-gnu/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=203de0ae33b53fee1578b117cb4123e85d0534f0, for GNU/Linux 3.2.0, stripped
> file /root/bundles/ubuntu-22.04/rootfs/usr/lib/x86_64-linux-gnu/libc.so.6 
/root/bundles/ubuntu-22.04/rootfs/usr/lib/x86_64-linux-gnu/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a43bfc8428df6623cd498c9c0caeb91aec9be4f9, for GNU/Linux 3.2.0, stripped
```

**Comment by lucabello** [comment]
So to clarify, does this require anything on my side?

**Comment by cjdcordeiro** [comment]
> So to clarify, does this require anything on my side?

it shouldn't. 22.04 has been updated upstream so I'm re-running the jobs

**Comment by cjdcordeiro** [comment]
actually, @lucabello can you please rebase your PR? there's something shady with the checks and when I re-run them they are picking additional stuff that they shouldn't

**Comment by lucabello** [comment]
Done!

**Review by cjdcordeiro — APPROVED** [review]
Thanks! Everything is green now :)

**Pull request merged**
