### PR TITLE
feat: add prometheus rock

### PR DESCRIPTION
**Pull request by lucabello**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](../CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
This PR adds the Prometheus ROCK to the **oci-factory**.

### Related issues
(none)

---

This PR is currently in a draft state while I go through the contribution guidelines, to allow for easier internal discussions!

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
NOTE: the `end-of-life` dates must be proper datetime ISO8601 strings

**Comment by lucabello** [comment]
I see! Indeed this is not an issue; I'll pause the work on this PR until all is ready on our repo's side!

**Comment by lucabello** [comment]
@cjdcordeiro 

After a long break due to our team having other priorities, I think this PR is ready to move forward now :)

After this gets merged expect more coming soon for our other rocks!

**Review by cjdcordeiro — APPROVED** [review]
hooray! this lgtm :)

Merging it. Please let me know if you get the MM notifications

**Comment by cjdcordeiro** [comment]
@lucabello the ROCKs failed to get published cause prometheus_2.45.0 has vulnerabilities. Can you please check https://github.com/canonical/oci-factory/actions/runs/5748505423 and assess? DM me if you need help. Worst case scenario we can whitelist those CVEs, but I'd rather do that with the proper due diligence in place

**Pull request merged**
