### PR TITLE
rename ROCK to rock

### PR DESCRIPTION
**Pull request by linostar**
- [x] I have signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] I am following the [CONTRIBUTING](https://github.com/canonical/oci-factory/blob/main/CONTRIBUTING.md) guidelines

*Ping the @canonical/rocks team.*

---

## Description
Replacing `ROCK` occurences by `rock`, with exception of the `ROCKS team`.

### CODE REVIEW

**Comment by linostar** [comment]
Tests are failing because we are modifying 5 oci images at the same time, whereas the test allows only one per PR.
However, given the nature of the changes in this PR, I think it's ok? @cjdcordeiro

**Comment by cjdcordeiro** [comment]
@linostar Well, we shouldn't change other people's images. Those are not ours to maintain. We can open an issue and assign it to each one of those maintainers. 

Otherwise, we might want to change them one by one, **but**, we MUST make sure the image builds don't get triggered! We can do it together next week.

**Comment by linostar** [comment]
Ok, I'll revert the changes related to those images. For each image, there are 1 or 2 occurences of the work "ROCK" at most, so it may not be worth it filing individual PRs and bothering the owners about it (except for mock-rock maybe!).

**Review by SamirPS — APPROVED** [review]

**Comment by cjdcordeiro** [comment]
> Ok, I'll revert the changes related to those images. For each image, there are 1 or 2 occurences of the work "ROCK" at most, so it may not be worth it filing individual PRs and bothering the owners about it (except for mock-rock maybe!).

y agreed. We can do it together, but we should still warn the maintainers cause they may have automated pipelines in place which might then start creating new PRs that either conflict to or revert our change.

**Comment by linostar** [comment]
> > Ok, I'll revert the changes related to those images. For each image, there are 1 or 2 occurences of the work "ROCK" at most, so it may not be worth it filing individual PRs and bothering the owners about it (except for mock-rock maybe!).
> 
> y agreed. We can do it together, but we should still warn the maintainers cause they may have automated pipelines in place which might then start creating new PRs that either conflict to or revert our change.

I will be filing individual PRs for each of the 5 rocks in order to both notify the owners and accomplish the desired renaming.

**Pull request merged**
